### ISSUE TITLE
[FEATURE] Footer-section Improvement

### ISSUE THREAD

**Issue by Compilearner** [Groverio/To-Do-List#108]
Description:
Changing the footer section background - color and the arrangement of Social media links , paragraph in it to make it better User-friendly.

**Comment by Anshul-18** [comment]
Hello, I will be happy to help you with the footer part(background - color and the arrangement of Social media links , paragraph) So can you assign this to me.

**Comment by Compilearner** [comment]
pls assign this issue to me , if you find it right.

**Comment by Anshul-18** [comment]
ok 👍

**Comment by Anurag-singh-thakur** [comment]
Can you assign it to me please

**Comment by Compilearner** [comment]
@Anshgrover23 Pls, check is it looking fine to you?? Or do you need any modifications??
When more links will be available, we can add them in the middle section  of footer.
![Screenshot (825)](https://github.com/user-attachments/assets/fc16b63d-a854-4f98-85cc-f281bf729920)
