### ISSUE TITLE
FEATURE: Changing the placeholder title to make the website more user friendly.

### ISSUE THREAD

**Issue by Shreyanshi210205** [Groverio/To-Do-List#33]
Issue
The  placeholder 'Share Your Thoughts' does not make clear to the user the actual use case of the box.
 
Solution:
By changing the placeholder 'Share Your Thoughts' to 'Task Description' will make the aim of that input box more concise and clear.

**Comment by Shreyanshi210205** [comment]
@Anshgrover23 I can change this feature 
Can you assign me this issue.

**Comment by bryans-go** [comment]
@Shreyanshi210205 you can do some efforts to resolve this and submit a PR.
