### ISSUE TITLE
New task complete button and confirmation that the task has been completed 

### ISSUE THREAD

**Issue by RohithNair27** [Groverio/To-Do-List#46]
**Is your feature request related to a problem? Please describe.**
1) No task completion button available
2) After task completion no message to show, completed status

**Describe the solution you'd like**
1) A card showing "well done on completing" and a complete button

Screenshot
![image](https://github.com/user-attachments/assets/bda194a7-762f-41b8-a9bb-dab891267f42)

**Comment by RohithNair27** [comment]
Assign this as hackOctober and give it to me, let me give it a shot

**Comment by bryans-go** [comment]
@RohithNair27 up to you. feel free to open a PR

**Comment by RohithNair27** [comment]
Hey kindly check and let me know if this works

**Comment by RohithNair27** [comment]
As this issue has been closed by other people closing this
